---
language: ruby
script: "bundle exec rake spec SPEC_OPTS='--format documentation'"
after_success:
  - git clone -q git://github.com/puppetlabs/ghpublisher.git .forge-release
  - .forge-release/publish
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
env:
  matrix:
  - PUPPET_GEM_VERSION="~> 2.7"
  - PUPPET_GEM_VERSION="~> 3.3"
  - PUPPET_GEM_VERSION="> 3.3"
  global:
  - PUBLISHER_LOGIN=puppetlabs
  -  secure: "FInoEwh3G4Auqp+OOdIc20lDLqrV6FHzWsM8ercHWjhDRD23VI49B1qqehWjaI8lKM3D5mTvdup23IVQBJo8M0rR/yfju1NhMYFTQ5bcJIrbQ3fn4n/zSaE8gLTOtHwzjSlqTJAYjxOAnp1VdMZngqpU/RYfSk68zJD34NqfovA="
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.7"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 2.7"
    - rvm: ruby-head
      env: PUPPET_GEM_VERSION="~> 2.7"
    - rvm: ruby-head
      env: PUPPET_GEM_VERSION="~> 3.3"
notifications:
  email: false
